POST http://127.0.0.1:3000/sessions/password
Content-Type: application/json

{
  "email": "alex2@spinova.co",
  "password": "sen123213"
}

###

GET http://127.0.0.1:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
Content-Type: application/json
