POST http://127.0.0.1:3000/sessions/password
Content-Type: application/json

{
  "email": "alex2@spinova.co",
  "password": "sen123213"
}

###

GET http://127.0.0.1:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTZmOWI4NS1iMzU3LTRhNGMtOTI2MC03OWI2ODVlZjM1NmYiLCJpYXQiOjE3NDQ4MTc3MzIsImV4cCI6MTc0NTQyMjUzMn0.fwAOmB2uZaBfptUtHJA55ODrpo6u9rHgIsAqYVqk6cM
Content-Type: application/json
